parser: babel-eslint
env:
  browser: true
  es6: true
  amd: true
  jest: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jest
  - react-hooks
globals:
  module: true
rules:
  react/jsx-uses-vars:
    - error
  react/prop-types:
    - warn
  react/display-name:
    - 0
  react-hooks/rules-of-hooks:
    - error
  no-console:
    - warn
  no-unused-vars:
    - warn
  # indent:
  #   - error
  #   - 4
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - error
  #   - single
  # semi:
  #   - warn
  #   - never
