Style/Documentation:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false

Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'